### PR TITLE
[YUNIKORN-781] Add  queue properties to the response of /ws/v1/partition/{partition}/queues

### PR DESCRIPTION
**Pull request by chia7712**
### What is this PR for?
That helps us observe the "application.sort.policy" through REST APIs. 

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-781

### How should this be tested?
`TestGetPartitionQueues`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by chia7712** [comment]
I will another PR to update the APIs doc (https://yunikorn.apache.org/docs/api/scheduler) after this PR is accepted

**Comment by yangwwei** [comment]
@manirajv06 can u help to review this PR?

**Review by yangwwei — APPROVED** [review]
looks @manirajv06 is not available right now.
this is a straightforward fix, looks good to me, thank you @chia7712 !

**Comment by manirajv06** [comment]
> looks @manirajv06 is not available right now.
> this is a straightforward fix, looks good to me, thank you @chia7712 !

Sorry for the delay. @chia7712 Can we modify TestGetPartitionQueuesHandler in handlers_test.go to cover this change as it would be more appropriate? Can we create a separate PR under this https://issues.apache.org/jira/browse/YUNIKORN-784 jira itself?

**Comment by chia7712** [comment]
>  Can we modify TestGetPartitionQueuesHandler in handlers_test.go to cover this change as it would be more appropriate?

sure

> Can we create a separate PR under this https://issues.apache.org/jira/browse/YUNIKORN-784 jira itself?

Did you mean "YUNIKORN-781"? YUNIKORN-784 is used to modify website doc.

**Comment by chia7712** [comment]
> Can we modify TestGetPartitionQueuesHandler in handlers_test.go to cover this change as it would be more appropriate?

https://github.com/apache/incubator-yunikorn-core/pull/293

**Pull request merged**
