### PR TITLE
[YUNIKORN-749] Adjust log level in the context for `processApplications`

### PR DESCRIPTION
**Pull request by jyz0309**
Signed-off-by: jyz0309 <45495947@qq.com>

### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
Adjust log level in the context for `processApplications` function

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
[YUNIKORN-749](https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-749?filter=allopenissues)
### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by wilfred-s** [comment]
I have just kicked off the build process. The change looks good to me as soon as the build comes back I add a review etc.

**Review by wilfred-s — CHANGES_REQUESTED** [review]
We have the same issue in the following methods:
* updateNodes (3 times)
* addNodes (2 times)
* processAsks (2 times)
* processAskReleases (1 time)

Would be good to get them all done in one go.

**Comment by jyz0309** [comment]
> We have the same issue in the following methods:
> 
> * updateNodes (3 times)
> * addNodes (2 times)
> * processAsks (2 times)
> * processAskReleases (1 time)
> 
> Would be good to get them all done in one go.

Ok! I will finish it today or tomorrow~

**Comment by jyz0309** [comment]
@wilfred-s Done~PTAL

**Review by wilfred-s — APPROVED** [review]
LGTM, will commit when build returns an OK

**Pull request closed without merging**
