### PR TITLE
[YUNIKORN-1065] panic on node update

### PR DESCRIPTION
**Pull request by wilfred-s**
### What is this PR for?
If a node is not found during the update logging causes a panic as it
refers to the wrong object. Fixed another possible panic in node
processing in the context. Unit tests added to cover the panic cases.

Fixed layout and formatting issues in error messages and comments

### What type of PR is it?
* [X] - Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1065

### How should this be tested?
Unit tests cover all problem cases.

### CODE REVIEW

**Review by manirajv06 — APPROVED** [review]
Looks good.

**Review by HuangTing-Yao — APPROVED** [review]
LGTM, I think we can close it after fix the HealthCheck UT problem.

**Comment by wilfred-s** [comment]
The unit test failure is caused by my change. The call to `metrics.Reset()` in the health tests does not work It is an empty function. The tests I added trigger a metrics update and thus cause the health tests to fail.
Implementing a proper rest of all metrics that can be reset.

**Review by craigcondit — APPROVED** [review]
+1 LGTM.

**Pull request closed without merging**
