### PR TITLE
[YUNIKORN-800] ensure consistent response between /ws/v1/partition/{par…

### PR DESCRIPTION
**Pull request by chia7712**
…titioName}/queue/{queueName}/applications and /ws/v1/apps

### What is this PR for?
In contrast to /ws/v1/apps, the response of /ws/v1/partition/{partitioName}/queue/{queueName}/applications excludes the completed applications.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-800

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by yangwwei** [comment]
@manirajv06 could u pls help to review this PR? thanks!

**Review by manirajv06 — COMMENTED** [review]
Overall approach looks good. Minor nits..

**Comment by chia7712** [comment]
@manirajv06 thanks for comment.

> Minor nits..

pardon me. I don't see any request changes.

**Review by manirajv06 — CHANGES_REQUESTED** [review]

**Comment by chia7712** [comment]
@manirajv06 thanks for all comments. I have addressed them. PTAL

**Review by manirajv06 — APPROVED** [review]

**Pull request merged**
