### PR TITLE
YUNIKORN-317. [Design Doc] Cache/Scheduler modules need to be combined to a single module

### PR DESCRIPTION
**Pull request by wangdatan**
Uploaded design doc. @yangwwei , @wilfred-s can you help to review?

### CODE REVIEW

**Comment by wangdatan** [comment]
While working on the refactoring, I want to make a few major changes to the organization of the package. Before that I'd like to hear your thoughts, especially @wilfred-s 

Existing package structure:

1) placement package highly depends on scheduler package (mostly data structure like schedulingApp/Queue, etc. of scheduler). 
2) scheduler.tests package depends on entry point (to initialize RMProxy). 

Proposed package structure: 

1) Move placement package into scheduler. (And its tests) 
2) Leave core e2e tests which need both RMProxy and Scheduler (tests invokes Entrypoint) to a separate package, such as `pkg/e2e`
3) Scheduler internal tests (Which doesn't depends on RMProxy) still inside scheduler package.

**Comment by wangdatan** [comment]
Added add a few more changes for what we discussed: 
1) Changes in scheduler to NOT async commit allocation (now commit is synced). 
2) Changes to remove all allocating resources, and other unused methods. 

What I plan to do next is make minimum changes to the test, and make sure at least the smoke test can run. After that, I think we will be good to continue develop this in a branch and stabilize it over time. Before that, I'd like to hear thoughts about package change proposed above.

All changes are pushed to my branch.

**Comment by wilfred-s** [comment]
I have move the PR to the new YUNIKORN-317 branch.
I will have a quick look at this and even push some changes in the new branch and we'll work on it there.

In the mean time I will work on getting the lint part of the build to pass on a branch (YUNIKORN-285)

**Comment by wangdatan** [comment]
@wilfred-s somehow I couldn't find my commits in the newly created YK-317 branch, I will continue work on this in my own branch, give me a few days, once I have done I will update this PR.

**Comment by wilfred-s** [comment]
Thank you for the work that you have done @wangdatan.

The change [committed here](https://github.com/apache/incubator-yunikorn-core/commit/7c37ccb383a430dcc6839fb26af057bddd50e5a5) does not include tests

I have rebased the change to the current head of the dev branch. I added changes on top to rewind the placement rules move into the scheduler package. This includes further refactoring.

**Pull request closed without merging**
