### PR TITLE
[YUNIKORN-374] Use same GRPC version in the core and the scheduler-interface

### PR DESCRIPTION
**Pull request by yangwwei**

### CODE REVIEW

**Comment by wilfred-s** [comment]
This change is looking at the GPRC version why are we making changes to the prometheus version also? The prometheus changes are handled under YUNIKORN-375. Can we split these two as per the jiras?

**Comment by yangwwei** [comment]
hi @wilfred-s sure. Let me split the changes. Now the change only include the gRPC version update. Pls take another look.

**Review by wilfred-s — CHANGES_REQUESTED** [review]
I think we need to also update the scheduler interface version in the mod file, we should first commit  apache/incubator-yunikorn-scheduler-interface#25
Beside that it looks good.

**Review by wilfred-s — APPROVED** [review]
lgtm, approved

**Pull request closed without merging**
